## ----------------------------------------------------------------
## Yutai Su(buaa_syt@126.com)
## One Element Generated by Abaqus Python script(C3D8)
## 24/11/2023
## ----------------------------------------------------------------
from part import *
from material import *
from section import *
from assembly import *
from step import *
from load import *
from mesh import *
from job import *
from sketch import *

# 0.0 Initialization
# 0.1 Model Name
ModelName="OneEleModel_C3D8"
# 0.2 Output Path
OutputPath="D:/temp/20231121_OneEle/"
# 0.3 Element size
EleSize=0.1
# 0.4 Time Period
TimePeriod=1.0
# 0.5 Increment interval and maximum increment number
Inc=0.01
MaxIncNum=10000
# 0.6 Maximum strain (final strain)
MaxStrain=0.05
# 0.7 Material properties
DesProp = ElaProp = UMATProp = False
USDFLDProp = OutVarProp = ConductProp = False
SHeatProp = CTEProp = SDVProp = False
PlasticProp = False
# If needed, please provide a value;
# if not needed, delete the variable below.
# 0.7.1 Density
DesProp=1.0
# 0.7.2 Elastic
ElaProp=[10100, 0.3]
# 0.7.3 UserMaterial
UMATProp=[1.0, 2.0, 3.0, 4.0, 56.0, 7.0, 8.0]
# 0.7.4 UserDefinedField
USDFLDProp=1
# 0.7.5 UserOutputVariables
OutVarProp=100
# 0.7.6 Conductivity
ConductProp=1.0
# 0.7.7 SpecificHeat
SHeatProp=1.0
# 0.7.8 Expansion
CTEProp=[0.000001, 298.15]
# 0.7.9 Depvar
SDVProp=240
# 0.7.10 Plastic
PlasticProp=[[1.0, 0.0],[1.2, 0.01],[1.0, 0.02]]

# 1.0 Modeling
# Model Establish
m=mdb.Model(modelType=STANDARD_EXPLICIT, name=ModelName)
# Geomety
s=m.ConstrainedSketch(name='__profile__', sheetSize=1.0)
p=m.Part(dimensionality=THREE_D, name='Part-1', type=DEFORMABLE_BODY)
s.rectangle(point1=(0.0, 0.0), point2=(EleSize, EleSize))
p.BaseSolidExtrude(depth=EleSize, sketch=s)
del s
# Set Definition
p.Set(cells=p.cells, name='Set-All')
p.Set(faces=p.faces.findAt(((EleSize/2.0,0,EleSize/2.0),)), name='Bottom')
p.Set(faces=p.faces.findAt(((EleSize/2.0,EleSize,EleSize/2.0),)), name='Top')
p.Set(faces=p.faces.findAt(((EleSize/2.0,EleSize/2.0,0),)), name='Right')
p.Set(faces=p.faces.findAt(((EleSize/2.0,EleSize/2.0,EleSize),)), name='Left')
p.Set(faces=p.faces.findAt(((0,EleSize/2.0,EleSize/2.0),)), name='Back')
p.Set(faces=p.faces.findAt(((EleSize,EleSize/2.0,EleSize/2.0),)), name='Front')
p.Set(vertices=p.vertices.findAt(((0.0,0.0,0.0),)), name='Point0')
# Material Properties
mat=m.Material(name='Material-1')
## Density
if DesProp:
    mat.Density(table=((DesProp, ), ))

## Elastic
if ElaProp:
    mat.Elastic(table=(ElaProp, ))

## User Material
if UMATProp:
    mat.UserMaterial(mechanicalConstants=UMATProp)

## User Defined Field
if USDFLDProp:
    mat.UserDefinedField()

## User Output Variables
if OutVarProp:
    mat.UserOutputVariables(n=OutVarProp)

## Conductivity
if ConductProp:
    mat.Conductivity(table=((ConductProp, ), ))

## Specific Heat
if SHeatProp:
    mat.SpecificHeat(table=((SHeatProp, ), ))

## Expansion
if CTEProp:
    mat.Expansion(table=((CTEProp[0], ), ), zero=CTEProp[1])

## Solution Dependent Variables
if SDVProp:
    mat.Depvar(n=SDVProp)

## Plastic
if PlasticProp:
    mat.Plastic(table=PlasticProp)

m.HomogeneousSolidSection(material='Material-1', name='Section-1', thickness=None)
p.SectionAssignment(offset=0.0, offsetField='', offsetType=MIDDLE_SURFACE, region=
    p.sets['Set-All'], sectionName='Section-1', thicknessAssignment=FROM_SECTION)
# Instances
a=m.rootAssembly
a.DatumCsysByDefault(CARTESIAN)
ins=a.Instance(dependent=ON, name='Part-1-1', part=p)
a.regenerate()
# Analysis Step
m.StaticStep(adaptiveDampingRatio=0.05, continueDampingFactors=False, name='Step-1', 
    nlgeom=ON, previous='Initial', initialInc=Inc, 
    maxInc=Inc, maxNumInc=MaxIncNum, minInc=1e-32, 
    stabilizationMagnitude=0.0002, stabilizationMethod=DISSIPATED_ENERGY_FRACTION, 
    timePeriod=TimePeriod)
m.FieldOutputRequest(createStepName='Step-1', name=
    'F-Output-1', timeInterval=Inc, variables=('S', 'E', 'U', 'RF', 'TEMP'))
del m.historyOutputRequests['H-Output-1']
# Bondary conditions
m.PinnedBC(createStepName='Initial', localCsys=None, 
    name='BC-1', region=ins.sets['Point0'])
m.DisplacementBC(amplitude=UNSET, createStepName='Initial', 
    distributionType=UNIFORM, fieldName='', localCsys=None, name='BC-2', 
    region=ins.sets['Bottom'], u1=UNSET, u2=SET, u3=UNSET, ur1=UNSET, 
    ur2=UNSET, ur3=UNSET)
m.DisplacementBC(amplitude=UNSET, createStepName='Initial', 
    distributionType=UNIFORM, fieldName='', localCsys=None, name='BC-3',
    region=ins.sets['Back'], u1=SET, u2=UNSET, u3=UNSET, ur1=UNSET, 
    ur2=UNSET, ur3=UNSET)
m.DisplacementBC(amplitude=UNSET, createStepName='Initial', 
    distributionType=UNIFORM, fieldName='', localCsys=None, name='BC-4', 
    region=ins.sets['Right'], u1=UNSET, u2=UNSET, u3=SET, ur1=UNSET, 
    ur2=UNSET, ur3=UNSET)
m.TabularAmplitude(data=((0.0, 0.0), (TimePeriod, MaxStrain*EleSize)), 
    name='Amp-1', smooth=SOLVER_DEFAULT, timeSpan=STEP)
m.DisplacementBC(amplitude='Amp-1', createStepName='Step-1', 
    distributionType=UNIFORM, fieldName='', fixed=OFF, localCsys=None, 
    name='BC-5', region=ins.sets['Top'], u1=UNSET, u2=1.0, u3=UNSET, 
    ur1=UNSET, ur2=UNSET, ur3=UNSET)
# Meshing
p.seedPart(deviationFactor=0.1, minSizeFactor=0.1, size=EleSize)
p.setMeshControls(elemShape=HEX, regions=p.cells)
p.setElementType(elemTypes=(ElemType(elemCode=C3D8, elemLibrary=STANDARD, 
    secondOrderAccuracy=OFF, distortionControl=DEFAULT), ), regions=(
    p.cells, ))
p.generateMesh()
# Job Generating
job=mdb.Job(atTime=None, contactPrint=OFF, description='', echoPrint=OFF, 
    explicitPrecision=SINGLE, getMemoryFromAnalysis=True, historyPrint=OFF, 
    memory=90, memoryUnits=PERCENTAGE, model=ModelName, modelPrint=OFF, 
    multiprocessingMode=DEFAULT, name=ModelName, nodalOutputPrecision=SINGLE, 
    numCpus=1, numGPUs=0, queue=None, resultsFormat=ODB, scratch='', type=
    ANALYSIS, userSubroutine='', waitHours=0, waitMinutes=0)

# 2.0 Outputs(INP, CAE, JNL)
mdb.saveAs(pathName="".join([OutputPath, ModelName]))
job.writeInput(consistencyChecking=OFF)
