## ----------------------------------------------------------------
## Yutai Su(buaa_syt@126.com)
## One Element Generated by Abaqus Python script(C3D8)
## 21/11/2023
## ----------------------------------------------------------------

# 0.0 Initialization
# 0.1 Define Model Name
ModelName = "OneEleModel_C3D8"
# 0.2 Define Output Path
OutputPath = "D:/temp/20231121_OneEle/"
# 0.4 Define Output Path
EleSize = 0.1
# 0.5 Define Output Path
TimePeriod = 1.0
# 0.6 Define Output Path
Inc = 0.01
MaxIncNum = 10000
# 0.7 Define Output Path
MaxStrain = 0.05
# 0.7 Material properties
# If needed, please provide a value;
# if not needed, delete the variable.
# 0.7.1 Density
DesProp = 1.0
# 0.7.2 Elastic
ElaProp = [10100, 0.3]
# 0.7.3 UserMaterial
UMATProp = [1.0, 2.0, 3.0, 4.0, 56.0, 7.0, 8.0]
# 0.7.4 UserDefinedField
USDFLDProp = 1
# 0.7.5 UserOutputVariables
OutVarProp = 100
# 0.7.6 Conductivity
ConductProp = 1.0
# 0.7.7 SpecificHeat
SHeatProp = 1.0
# 0.7.8 Expansion
CTEProp = [0.000001, 298.15]
# 0.7.9 Depvar
SDVProp = 240
# 0.7.10 Plastic
PlasticProp = [[1.0, 0.0], [1.2, 0.01], [1.0, 0.02]]

# 1.0 Modeling
# 1.1 loading inp files
inp0 = open("c3d8.inp", "r").readlines()
inp1 = open(OutputPath+ModelName+".inp", "w")
# 1.2 Element Size Update
inp0[8] = "1, "+str(EleSize)+", "+str(EleSize)+", "+str(EleSize)+"\n"
inp0[9] = "2, "+str(EleSize)+", 0., "+str(EleSize)+"\n"
inp0[10] = "3, "+str(EleSize)+", "+str(EleSize)+", 0.\n"
inp0[11] = "4, "+str(EleSize)+", 0., 0.\n"
inp0[12] = "5, 0., "+str(EleSize)+"\n"
inp0[13] = "6, 0., 0., "+str(EleSize)+"\n"
inp0[14] = "7, 0., "+str(EleSize)+", 0.\n"
inp0[15] = "8, 0., 0., 0.\n"
# 1.3 Boundary conditions
inp0[58] = "0., 0., "+str(TimePeriod)+", "+str(MaxStrain*EleSize)+"\n"
# 1.4 Analysis step
inp0[75] = "*Step, name=Step-1, nlgeom=YES, inc="+str(MaxIncNum)+"\n"
inp0[77] = str(Inc)+", "+str(TimePeriod)+", 1e-32, "+str(Inc)+"\n"
inp0[85] = "*Output, field, time interval="+str(TimePeriod*Inc)+"\n"
# 1.5 Material properties
## Density
try:
    mat.Density(table=((DesProp, ), ))
except:
    print("No density.")

## Elastic
try:
    mat.Elastic(table=(ElaProp, ))
except:
    print("No Elastic.")

## User Material
try:
    mat.UserMaterial(mechanicalConstants=UMATProp)
except:
    print("No User Material.")

## User Defined Field
try:
    mat.UserDefinedField()
except:
    print("No User Defined Field.")

## User Output Variables
try:
    mat.UserOutputVariables(n=OutVarProp)
except:
    print("No User Output Variables.")

## Conductivity
try:
    mat.Conductivity(table=((ConductProp, ), ))
except:
    print("No Conductivity.")

## Specific Heat
try:
    mat.SpecificHeat(table=((SHeatProp, ), ))
except:
    print("No Specific Heat.")

## Expansion
try:
    mat.Expansion(table=((CTEProp[0], ), ), zero=CTEProp[1])
except:
    print("No Expansion.")

## Solution Dependent Variables
try:
    mat.Depvar(n=SDVProp)
except:
    print("No Solution Dependent Variables.")

## Plastic
try:
    mat.Plastic(table=PlasticProp)
except:
    print("No Plastic.")



inp0.insert(61, "------0------\n")
inp0.insert(62, "------1------\n")
inp0.insert(63, "------3------\n")
inp0.insert(64, "------4------\n")
# 2.0 Outputs(INP)
for i in range(len(inp0)):
    inp1.write(inp0[i])
inp1.close()
